export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_POKEMONS_PENDING = 'REQUEST_POKEMONS_PENDING';
export const REQUEST_POKEMONS_SUCCESS = 'REQUEST_POKEMONS_SUCCESS';
export const REQUEST_POKEMONS_FAILED = 'REQUEST_POKEMONS_FAILED';

export const RETURN_TABLE = 'RETURN_FILTER';

export const CHANGE_HEIGHT_FILTER = 'CHANGE_HEIGHT_FILTER';
export const CHANGE_WEAKNESSES_FILTER = 'CHANGE_WEAKNESSES_FILTER';
