export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_POKEMONS_PENDING = 'REQUEST_POKEMONS_PENDING';
export const REQUEST_POKEMONS_SUCCESS = 'REQUEST_POKEMONS_SUCCESS';
export const REQUEST_POKEMONS_FAILED = 'REQUEST_POKEMONS_FAILED';

// export const FILTER_POKEMONS_SUCCESS = 'FILTER_POKEMONS_SUCCESS';
// export const FILTER_POKEMONS_FAILED = 'FILTER_POKEMONS_FAILED';

export const RETURN_TABLE = 'RETURN_FILTER';
